let cinemaEvents=[];const el=id=>document.getElementById(id);
function normalize(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function startOfToday(){const d=new Date();d.setHours(0,0,0,0);return d}
function addDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d}
function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function formatHeaderDay(date){let s=new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"short"}).format(date);return s.charAt(0).toUpperCase()+s.slice(1)}
function formatTime(date){return new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(date)}
function isWeekday(date){const d=date.getDay();return d>=1&&d<=5}
function selectedCinemas(){const c=el("cinemaFilters");if(!c)return new Set();return new Set([...c.querySelectorAll('input[type="checkbox"]:checked')].map(i=>i.value))}
function cinemaGroupName(name){return(name==="Méliès Jean-Jaurès"||name==="Méliès Saint-François")?"Méliès":(name||"Cinéma")}
function sessionCinemaClass(session){if(session.cinema==="Méliès Saint-François")return"session-sf";if(session.cinema==="Méliès Jean-Jaurès")return"session-jj";return""}
function buildCinemaFilters(){const c=el("cinemaFilters");if(!c)throw new Error("#cinemaFilters absent");c.innerHTML="";const names=[...new Set(cinemaEvents.map(e=>e.cinema).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"fr"));for(const name of names){const l=document.createElement("label");l.className="cinema-filter-check";const i=document.createElement("input");i.type="checkbox";i.value=name;i.addEventListener("change",render);const s=document.createElement("span");s.textContent=name;l.append(i,s);c.appendChild(l)}}
function buildDayHeaders(days){const r=el("cinemaWeekHeader");if(!r)throw new Error("#cinemaWeekHeader absent");r.innerHTML='<th class="film-col">Film / cinéma</th>';const t=startOfToday();for(const d of days){const th=document.createElement("th");th.className="day-col";if(sameDay(d,t))th.classList.add("today-col");th.textContent=formatHeaderDay(d);r.appendChild(th)}}
function visibleEvents(){const search=normalize(el("cinemaSearch")?.value||"");const after=el("afterWorkOnly")?.checked||false;const cinemas=selectedCinemas();const start=startOfToday(),end=addDays(start,5);return cinemaEvents.filter(e=>{const d=new Date(e.start);if(Number.isNaN(d.getTime())||d<start||d>=end)return false;if(after&&isWeekday(d)&&d.getHours()<17)return false;if(cinemas.size>0&&!cinemas.has(e.cinema))return false;if(search&&!normalize(e.title).includes(search))return false;return true})}
function groupByFilmThenCinema(events){const films=new Map();for(const e of events){const k=normalize(e.title);if(!films.has(k))films.set(k,{title:e.title,cinemas:new Map()});const f=films.get(k),ck=cinemaGroupName(e.cinema);if(!f.cinemas.has(ck))f.cinemas.set(ck,[]);f.cinemas.get(ck).push(e)}return[...films.values()].sort((a,b)=>{const ca=[...a.cinemas.values()].reduce((s,x)=>s+x.length,0),cb=[...b.cinemas.values()].reduce((s,x)=>s+x.length,0);return cb!==ca?cb-ca:a.title.localeCompare(b.title,"fr")})}
function filmSessionCount(f){return[...f.cinemas.values()].reduce((s,x)=>s+x.length,0)}
function createSessionNode(session){const d=new Date(session.start);const n=document.createElement(session.url?"a":"span");const cc=sessionCinemaClass(session);n.className=cc?`session-time ${cc}`:"session-time";if(session.url){n.href=session.url;n.target="_blank";n.rel="noopener"}const h=document.createElement("span");h.textContent=formatTime(d);n.appendChild(h);if(session.version){const v=document.createElement("span");v.className="session-version";v.textContent=session.version;n.appendChild(v)}return n}
function renderSessionCell(td,sessions){if(!sessions.length){const e=document.createElement("span");e.className="no-session";e.textContent="—";td.appendChild(e);return 0}sessions.sort((a,b)=>new Date(a.start)-new Date(b.start));const list=document.createElement("div");list.className="session-list";for(const s of sessions)list.appendChild(createSessionNode(s));td.appendChild(list);return sessions.length}
function renderMainTable(films,days){const body=el("cinemaWeekBody");if(!body)throw new Error("#cinemaWeekBody absent");body.innerHTML="";const today=startOfToday();let total=0;for(const film of films){const entries=[...film.cinemas.entries()].sort((a,b)=>a[0].localeCompare(b[0],"fr"));entries.forEach(([cinema,sessions],index)=>{const tr=document.createElement("tr");tr.className=index===0?"film-start-row":"film-sub-row";const first=document.createElement("td");first.className="film-col";if(index===0){const t=document.createElement("span");t.className="film-title";t.textContent=film.title;first.appendChild(t)}const c=document.createElement("span");c.className="film-cinema";c.textContent=cinema;first.appendChild(c);tr.appendChild(first);for(const day of days){const td=document.createElement("td");td.className="sessions-cell";if(sameDay(day,today))td.classList.add("today-col");const ds=sessions.filter(s=>sameDay(new Date(s.start),day));total+=renderSessionCell(td,ds);tr.appendChild(td)}body.appendChild(tr)})}if(!films.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=6;td.className="cinema-empty";td.textContent="Aucun film avec au moins 5 séances.";tr.appendChild(td);body.appendChild(tr)}return total}
function renderOccasional(films){const c=el("cinemaOccasional"),sec=el("cinemaOccasionalSection");if(!c||!sec)return 0;c.innerHTML="";if(!films.length){sec.style.display="none";return 0}sec.style.display="";const list=document.createElement("div");list.className="occasional-list";let total=0;for(const film of films){const row=document.createElement("div");row.className="occasional-row";const title=document.createElement("span");title.className="occasional-title";title.textContent=film.title;row.appendChild(title);const wrap=document.createElement("div");wrap.className="occasional-sessions";const sessions=[...film.cinemas.values()].flat().sort((a,b)=>new Date(a.start)-new Date(b.start));sessions.forEach((s,index)=>{total++;if(index>0){const sep=document.createElement("span");sep.className="occasional-separator";sep.textContent=",";wrap.appendChild(sep)}const d=new Date(s.start);const date=document.createElement("span");date.className="occasional-date";date.textContent=formatHeaderDay(d);wrap.append(date,createSessionNode(s))});row.appendChild(wrap);list.appendChild(row)}c.appendChild(list);return total}
function render(){const start=startOfToday();const days=Array.from({length:5},(_,i)=>addDays(start,i));buildDayHeaders(days);const films=groupByFilmThenCinema(visibleEvents());const main=films.filter(f=>filmSessionCount(f)>=5);const occasional=films.filter(f=>filmSessionCount(f)<5);const total=renderMainTable(main,days)+renderOccasional(occasional);const status=el("cinemaStatus");if(status)status.textContent=`${films.length} film${films.length>1?"s":""} · ${total} séance${total>1?"s":""}`}
async function init(){try{const r=await fetch("cinema_events.json",{cache:"no-store"});if(!r.ok)throw new Error("Impossible de charger cinema_events.json");cinemaEvents=await r.json();if(!Array.isArray(cinemaEvents))throw new Error("cinema_events.json n'a pas le bon format");cinemaEvents.sort((a,b)=>new Date(a.start)-new Date(b.start));buildCinemaFilters();render()}catch(err){console.error(err);const s=el("cinemaStatus");if(s)s.textContent="Erreur : "+err.message}}
el("cinemaSearch")?.addEventListener("input",render);el("afterWorkOnly")?.addEventListener("change",render);init();
